"""GENERATED by ../Clip to DWG/build_standalone.py from
Toms Toolbar/common/box_map_tool.py - do not edit this copy, edit that one.
"""
"""
Shared two-click / click-drag bounding-box map tool.

A rubber band follows the cursor; the user either clicks two opposite corners
or click-drags a box (>= 50 px). On completion `on_complete(QgsRectangle)` is
called; Escape or right-click calls `on_cancel()`. The rectangle is in the
map (project) CRS.

Originally three identical copies lived in Clip to DWG, Clip to XYZ and
Restore DEM — amalgamated here so all of Tom's Toolbar shares one tool.
"""
from qgis.PyQt.QtCore import Qt
from qgis.PyQt.QtGui import QColor, QCursor
from qgis.core import (
    Qgis, QgsMessageLog, QgsPointXY, QgsRectangle, QgsWkbTypes,
)
from qgis.gui import QgsMapTool, QgsRubberBand


class BoxMapTool(QgsMapTool):
    DRAG_THRESHOLD_PX = 50

    def __init__(self, canvas, on_complete, on_cancel):
        super().__init__(canvas)
        self.canvas = canvas
        self.on_complete = on_complete
        self.on_cancel = on_cancel
        self.first_point = None
        self.press_screen_pos = None

        self.rubber_band = QgsRubberBand(
            canvas, QgsWkbTypes.GeometryType.PolygonGeometry)
        self.rubber_band.setColor(QColor(255, 0, 0, 200))
        self.rubber_band.setFillColor(QColor(255, 0, 0, 40))
        self.rubber_band.setWidth(2)

        self.setCursor(QCursor(Qt.CursorShape.CrossCursor))

    def canvasPressEvent(self, event):
        if event.button() == Qt.MouseButton.RightButton:
            self._cancel()
            return
        if event.button() != Qt.MouseButton.LeftButton:
            return

        point = self.toMapCoordinates(event.pos())
        if self.first_point is None:
            self.first_point = point
            self.press_screen_pos = event.pos()
        else:
            rect = QgsRectangle(self.first_point, point)
            self._cleanup()
            self.on_complete(rect)

    def canvasReleaseEvent(self, event):
        if event.button() != Qt.MouseButton.LeftButton:
            return
        if self.first_point is None or self.press_screen_pos is None:
            return
        delta = event.pos() - self.press_screen_pos
        dist = (delta.x() ** 2 + delta.y() ** 2) ** 0.5
        if dist < self.DRAG_THRESHOLD_PX:
            # Treat as the first click of two-click mode. Keep first_point.
            return
        point = self.toMapCoordinates(event.pos())
        rect = QgsRectangle(self.first_point, point)
        self._cleanup()
        self.on_complete(rect)

    def canvasMoveEvent(self, event):
        if self.first_point is None:
            return
        current = self.toMapCoordinates(event.pos())
        self._draw_rect(self.first_point, current)

    def keyPressEvent(self, event):
        if event.key() == Qt.Key.Key_Escape:
            self._cancel()

    def _draw_rect(self, p1, p2):
        self.rubber_band.reset(QgsWkbTypes.GeometryType.PolygonGeometry)
        corners = [
            QgsPointXY(p1.x(), p1.y()),
            QgsPointXY(p2.x(), p1.y()),
            QgsPointXY(p2.x(), p2.y()),
            QgsPointXY(p1.x(), p2.y()),
        ]
        for pt in corners:
            self.rubber_band.addPoint(pt, False)
        # close polygon with do_update=True to repaint
        self.rubber_band.addPoint(corners[0], True)

    def _cleanup(self):
        self.rubber_band.reset(QgsWkbTypes.GeometryType.PolygonGeometry)
        self.canvas.unsetMapTool(self)

    def _cancel(self):
        self._cleanup()
        self.on_cancel()
        # Esc / right-click -> fall back to hand pan (AutoCAD-style)
        try:
            from qgis.utils import iface
            if iface is not None:
                iface.actionPan().trigger()
        except (AttributeError, RuntimeError, ImportError) as exc:
            # only the convenience fall-back to Pan; the tool is already
            # disarmed, so this is cosmetic - but do not do it in silence
            QgsMessageLog.logMessage(
                "falling back to the Pan tool failed ({}: {})".format(
                    type(exc).__name__, exc),
                "Tom's Toolbar", Qgis.MessageLevel.Warning)

    def deactivate(self):
        self.rubber_band.reset(QgsWkbTypes.GeometryType.PolygonGeometry)
        super().deactivate()
