"""Clip to DWG - standalone plugin host.

GENERATED by ../Clip to DWG/build_standalone.py - do not edit this copy.

The tool itself is shared verbatim with Tom's Toolbar; all this does is give it
a toolbar and a menu entry of its own.
"""
from qgis.core import Qgis, QgsMessageLog

from .tool import ClipToDwgTool

MENU = "Clip to DWG"


class ClipToDwgPlugin:
    def __init__(self, iface):
        self.iface = iface
        self.toolbar = None
        self.tool = None
        self.menu_actions = []

    def initGui(self):
        self.toolbar = self.iface.addToolBar(MENU)
        self.toolbar.setObjectName("ClipToDwg")
        self.toolbar.setToolTip(MENU)
        self.tool = ClipToDwgTool(self.iface)
        for act in self.tool.actions:
            self.toolbar.addAction(act)
            self.iface.addPluginToMenu(MENU, act)
            self.menu_actions.append(act)

    def unload(self):
        for act in self.menu_actions:
            self.iface.removePluginMenu(MENU, act)
        self.menu_actions = []
        unload = getattr(self.tool, "unload", None)
        if unload is not None:
            try:
                unload()
            except Exception as exc:  # noqa: BLE001
                # QGIS is tearing the plugin down; refusing to finish here
                # would leave the toolbar behind, so carry on - but say so.
                QgsMessageLog.logMessage(
                    "tool unload failed ({}: {}) - continuing teardown".format(
                        type(exc).__name__, exc),
                    MENU, Qgis.MessageLevel.Warning)
        if self.toolbar is not None:
            self.iface.mainWindow().removeToolBar(self.toolbar)
            self.toolbar.deleteLater()
            self.toolbar = None
        self.tool = None
