"""Clip to DWG - standalone plugin host.

GENERATED by ../Clip to DWG/build_standalone.py - do not edit this copy.

The tool itself is shared verbatim with Tom's Toolbar; all this does is give it
a toolbar and a menu entry of its own.
"""
from .tool import ClipToDwgTool

MENU = "Clip to DWG"


class ClipToDwgPlugin:
    def __init__(self, iface):
        self.iface = iface
        self.toolbar = None
        self.tool = None
        self.menu_actions = []

    def initGui(self):
        self.toolbar = self.iface.addToolBar(MENU)
        self.toolbar.setObjectName("ClipToDwg")
        self.toolbar.setToolTip(MENU)
        self.tool = ClipToDwgTool(self.iface)
        for act in self.tool.actions:
            self.toolbar.addAction(act)
            self.iface.addPluginToMenu(MENU, act)
            self.menu_actions.append(act)

    def unload(self):
        for act in self.menu_actions:
            self.iface.removePluginMenu(MENU, act)
        self.menu_actions = []
        if hasattr(self.tool, "unload"):
            try:
                self.tool.unload()
            except Exception:  # noqa: BLE001
                pass
        if self.toolbar is not None:
            self.iface.mainWindow().removeToolBar(self.toolbar)
            self.toolbar.deleteLater()
            self.toolbar = None
        self.tool = None
