"""GENERATED by ../Clip to DWG/build_standalone.py from
Toms Toolbar/clip_dwg/preflight.py - do not edit this copy, edit that one.
"""
"""Clip to DWG - work out what is actually going to be exported, before it is.

Split out from the dialog so it can be checked headlessly (tests/
test_clip_dwg_preflight.py). No Qt widgets in here.

The whole point of this module is that the old one-liner

    [l for l in root.checkedLayers() if l.type() == QgsMapLayer.VectorLayer]

quietly lost layers. Two ways:

* A group set to **"Render Layers as a Group"** (QgsGroupLayer, 3.24+) is
  returned by `checkedLayers()` as ONE composite layer instead of its children,
  and that composite is not a vector layer - so the filter above dropped the
  group and everything in it. Tom's TUFLOW groups use this, and it is the same
  trap that hid layers from Pick Layer. Verified 2026-09-16: a tree of
  TOP / GRP(A, B) / BOT gave `checkedLayers() -> ['TOP', 'GRP']` once GRP was
  converted, while `findLayers()` still gave `['TOP', 'A', 'B', 'BOT']`.
* `node.isVisible()` is no use as a substitute - on 3.44 it returns False for
  every node, rendered ones included.

So: enumerate `findLayers()` and decide checked-ness by walking
`itemVisibilityChecked()` up the parent chain.

Scale-dependent visibility is deliberately IGNORED. A layer that is ticked but
scale-hidden still exports: Tom's call, and the right one - the box you drew
has nothing to do with the zoom you happened to be at.
"""
from qgis.core import (
    QgsCoordinateTransform,
    QgsFeatureRequest,
    QgsMapLayer,
    QgsProject,
    QgsRenderContext,
    QgsWkbTypes,
)

# Approximate counts stop being worth the wait past this many candidates.
COUNT_CAP = 200000


def node_checked(node):
    """True when this node and every group above it are ticked."""
    while node is not None:
        checked = getattr(node, "itemVisibilityChecked", None)
        if checked is not None and not checked():
            return False
        node = node.parent()
    return True


def _order_key(root):
    """Map layer id -> position for draw order, or None to use tree order.

    A user-set custom layer order wins. Unlike `layerOrder()`, which swallows
    group-layer children, `customLayerOrder()` lists them individually
    (verified 2026-09-16), so it is safe to use directly.
    """
    try:
        if not root.hasCustomLayerOrder():
            return None
        return {l.id(): i for i, l in enumerate(root.customLayerOrder())
                if l is not None}
    except Exception:  # noqa: BLE001
        return None


def export_layers(project=None):
    """Ticked vector layers in Layers-panel order, TOP first.

    That is the order to show the user. The exporter reverses it before handing
    the layers to QgsDxfExport, because CAD draws later entities over earlier
    ones - so writing the bottom layer first leaves the top of the Layers panel
    on top in the DWG, which is what "the same as the canvas" means to anyone
    looking at it.
    """
    project = project or QgsProject.instance()
    root = project.layerTreeRoot()
    order = _order_key(root)

    found = []
    for pos, node in enumerate(root.findLayers()):
        layer = node.layer()
        if layer is None or layer.type() != QgsMapLayer.VectorLayer:
            continue
        if not node_checked(node):
            continue
        rank = pos if order is None else order.get(layer.id(), pos)
        found.append((rank, pos, layer))

    found.sort(key=lambda t: (t[0], t[1]))
    return [layer for _, _, layer in found]


def has_visible_fill(layer):
    """True if any enabled fill symbol layer would actually paint something.

    Mirrors the test `tool._disable_invisible_symbol_layers` applies: a fully
    transparent colour or a NoBrush style paints nothing, so QgsDxfExport
    writes no HATCH for it. Correct behaviour, but worth saying out loud in
    the pre-flight rather than letting it surprise anyone in CAD.
    """
    renderer = layer.renderer()
    if renderer is None:
        return False
    try:
        symbols = renderer.symbols(QgsRenderContext())
    except Exception:  # noqa: BLE001
        return True          # can't tell - assume it paints, never under-report
    for symbol in symbols or []:
        if symbol is None:
            continue
        try:
            count = symbol.symbolLayerCount()
        except Exception:  # noqa: BLE001
            continue
        for i in range(count):
            try:
                sl = symbol.symbolLayer(i)
            except Exception:  # noqa: BLE001
                continue
            if sl is None:
                continue
            try:
                if not sl.enabled():
                    continue
            except Exception:  # noqa: BLE001
                pass
            brush = getattr(sl, "brushStyle", None)
            if brush is not None:
                try:
                    if int(brush()) == 0:       # Qt.NoBrush
                        continue
                except Exception:  # noqa: BLE001
                    pass
            fill = getattr(sl, "fillColor", None)
            colour = None
            try:
                colour = fill() if fill is not None else sl.color()
            except Exception:  # noqa: BLE001
                colour = None
            if colour is not None and colour.alpha() == 0:
                continue
            if fill is not None or brush is not None:
                return True
    return False


def count_in_box(layer, rect, project_crs, cap=COUNT_CAP):
    """Roughly how many features fall in the box, using the layer's index.

    A bounding-box request, so it over-reports features whose envelope clips
    the box but whose geometry does not - close enough for a pre-flight, and
    it costs nothing on an indexed source. Returns (count, capped).
    """
    try:
        box = rect
        if (layer.crs().isValid() and project_crs.isValid()
                and layer.crs() != project_crs):
            tr = QgsCoordinateTransform(project_crs, layer.crs(),
                                        QgsProject.instance())
            box = tr.transformBoundingBox(rect)
        req = QgsFeatureRequest().setFilterRect(box).setNoAttributes()
        flags = getattr(QgsFeatureRequest, "NoGeometry", None)
        if flags is not None:
            req.setFlags(flags)
        n = 0
        for _ in layer.getFeatures(req):
            n += 1
            if n >= cap:
                return n, True
        return n, False
    except Exception:  # noqa: BLE001
        return -1, False


def describe(layer, rect, project_crs):
    """One pre-flight row: what this layer is, and what it will produce."""
    gtype = layer.geometryType()
    is_polygon = gtype == QgsWkbTypes.PolygonGeometry
    count, capped = count_in_box(layer, rect, project_crs)

    blocker = ""
    if not layer.isValid():
        blocker = "layer is broken and cannot be read"
    elif not layer.crs().isValid():
        # Left to QGIS this surfaces as an unexplained projection dialog in
        # the middle of the export, with nothing to say which layer caused it.
        blocker = "no CRS - cannot be placed, will be skipped"

    notes = []
    if not blocker:
        if count == 0:
            notes.append("nothing inside the box")
        if is_polygon and not has_visible_fill(layer):
            notes.append("no fill on canvas, so outlines only - no hatches")

    return {
        "layer": layer,
        "name": layer.name(),
        "geometry": QgsWkbTypes.geometryDisplayString(gtype)
                    if gtype is not None else "?",
        "is_polygon": is_polygon,
        "count": count,
        "capped": capped,
        "crs": layer.crs().authid() or layer.crs().description() or "",
        "blocker": blocker,
        "notes": notes,
        "include": not blocker and count != 0,
    }


def preflight(rect, project_crs, project=None):
    """describe() every layer that would be exported, in draw order."""
    return [describe(l, rect, project_crs) for l in export_layers(project)]
