"""GENERATED by ../Clip to DWG/build_standalone.py from
Toms Toolbar/clip_dwg/preflight.py - do not edit this copy, edit that one.
"""
"""Clip to DWG - work out what is actually going to be exported, before it is.

Split out from the dialog so it can be checked headlessly (tests/
test_clip_dwg_preflight.py). No Qt widgets in here.

The whole point of this module is that the old one-liner

    [lyr for lyr in root.checkedLayers()
     if lyr.type() == QgsMapLayer.LayerType.VectorLayer]

quietly lost layers. Two ways:

* A group set to **"Render Layers as a Group"** (QgsGroupLayer, 3.24+) is
  returned by `checkedLayers()` as ONE composite layer instead of its children,
  and that composite is not a vector layer - so the filter above dropped the
  group and everything in it. Tom's TUFLOW groups use this, and it is the same
  trap that hid layers from Pick Layer. Verified 2026-09-16: a tree of
  TOP / GRP(A, B) / BOT gave `checkedLayers() -> ['TOP', 'GRP']` once GRP was
  converted, while `findLayers()` still gave `['TOP', 'A', 'B', 'BOT']`.
* `node.isVisible()` is no use as a substitute - on 3.44 it returns False for
  every node, rendered ones included.

So: enumerate `findLayers()` and decide checked-ness by walking
`itemVisibilityChecked()` up the parent chain.

Scale-dependent visibility is deliberately IGNORED. A layer that is ticked but
scale-hidden still exports: Tom's call, and the right one - the box you drew
has nothing to do with the zoom you happened to be at.
"""
from qgis.PyQt.QtCore import Qt
from qgis.core import (
    Qgis,
    QgsCoordinateTransform,
    QgsFeatureRequest,
    QgsMapLayer,
    QgsMessageLog,
    QgsProject,
    QgsRenderContext,
    QgsWkbTypes,
)

LOG_TAG = "Clip to DWG"

# Approximate counts stop being worth the wait past this many candidates.
COUNT_CAP = 200000

# Reaching into a QGIS symbol layer can fail three ways that are NOT bugs: the
# method does not exist on this QGIS version (AttributeError), it wants
# different arguments (TypeError), or the underlying C++ object has already
# been deleted (RuntimeError). Those are tolerated and written down. Anything
# else is a real fault and is allowed to escape rather than be swallowed.
API_MISS = (AttributeError, TypeError, RuntimeError)


def note(what, exc):
    """Record a tolerated failure instead of passing over it in silence.

    Silence is what let the group-layer bug hide for four months, and it is
    what a security scanner objects to in a bare `except: pass`.
    """
    QgsMessageLog.logMessage(
        "{} failed ({}: {}) - continuing".format(
            what, type(exc).__name__, exc),
        LOG_TAG, Qgis.MessageLevel.Warning)


def node_checked(node):
    """True when this node and every group above it are ticked."""
    while node is not None:
        checked = getattr(node, "itemVisibilityChecked", None)
        if checked is not None and not checked():
            return False
        node = node.parent()
    return True


def _order_key(root):
    """Map layer id -> position for draw order, or None to use tree order.

    A user-set custom layer order wins. Unlike `layerOrder()`, which swallows
    group-layer children, `customLayerOrder()` lists them individually
    (verified 2026-09-16), so it is safe to use directly.
    """
    try:
        if not root.hasCustomLayerOrder():
            return None
        return {lyr.id(): i
                for i, lyr in enumerate(root.customLayerOrder())
                if lyr is not None}
    except API_MISS as exc:
        note("root.customLayerOrder()", exc)
        return None


def export_layers(project=None):
    """Ticked vector layers in Layers-panel order, TOP first.

    That is the order to show the user. The exporter reverses it before handing
    the layers to QgsDxfExport, because CAD draws later entities over earlier
    ones - so writing the bottom layer first leaves the top of the Layers panel
    on top in the DWG, which is what "the same as the canvas" means to anyone
    looking at it.
    """
    project = project or QgsProject.instance()
    root = project.layerTreeRoot()
    order = _order_key(root)

    found = []
    for pos, node in enumerate(root.findLayers()):
        layer = node.layer()
        if layer is None or layer.type() != QgsMapLayer.LayerType.VectorLayer:
            continue
        if not node_checked(node):
            continue
        rank = pos if order is None else order.get(layer.id(), pos)
        found.append((rank, pos, layer))

    found.sort(key=lambda t: (t[0], t[1]))
    return [layer for _, _, layer in found]


def symbol_layers(renderer):
    """(readable, [symbol layers]) for every symbol in a renderer.

    One place for the defensive probing that used to be copy-pasted into three
    near-identical walks - which is where most of a security scanner's
    complaints about swallowed exceptions came from. `readable` is False only
    when the renderer could not be read at all, which callers use to avoid
    stating an answer they have not actually got.
    """
    out = []
    if renderer is None:
        return True, out
    try:
        symbols = renderer.symbols(QgsRenderContext()) or []
    except API_MISS as exc:
        note("renderer.symbols()", exc)
        return False, out
    for symbol in symbols:
        if symbol is None:
            continue
        try:
            count = symbol.symbolLayerCount()
        except API_MISS as exc:
            note("symbol.symbolLayerCount()", exc)
            continue
        for i in range(count):
            try:
                sl = symbol.symbolLayer(i)
            except API_MISS as exc:
                note("symbol.symbolLayer({})".format(i), exc)
                continue
            if sl is not None:
                out.append(sl)
    return True, out


def symbol_layer_enabled(sl):
    """Whether the user has left this symbol layer switched on. Unreadable
    counts as on - never drop something because a probe failed."""
    try:
        return bool(sl.enabled())
    except API_MISS as exc:
        note("symbolLayer.enabled()", exc)
        return True


def paints_nothing(sl):
    """The invisibility test the exporter applies before disabling a symbol
    layer: a fully transparent colour, a NoBrush style, or a fully transparent
    fill colour. Kept exactly as it was - this decides what reaches CAD."""
    invisible = False
    try:
        colour = sl.color()
        if colour is not None and colour.alpha() == 0:
            invisible = True
    except API_MISS as exc:
        note("symbolLayer.color()", exc)
    brush = getattr(sl, "brushStyle", None)
    if brush is not None:
        try:
            if brush() == Qt.BrushStyle.NoBrush:
                invisible = True
        except API_MISS as exc:
            note("symbolLayer.brushStyle()", exc)
    fill = getattr(sl, "fillColor", None)
    if fill is not None:
        try:
            fc = fill()
            if fc is not None and fc.alpha() == 0:
                invisible = True
        except API_MISS as exc:
            note("symbolLayer.fillColor()", exc)
    return invisible


def has_visible_fill(layer):
    """True if any enabled fill symbol layer would actually paint something.

    A fully transparent colour or a NoBrush style paints nothing, so
    QgsDxfExport writes no HATCH for it. Correct behaviour, but worth saying
    out loud in the pre-flight rather than letting it surprise anyone in CAD.

    Deliberately NOT the same test as `paints_nothing`: that one also treats a
    transparent stroke colour as invisible, which is right for deciding what to
    disable but wrong for deciding whether a hatch appears.
    """
    renderer = layer.renderer()
    if renderer is None:
        return False
    readable, sym_layers = symbol_layers(renderer)
    if not readable:
        # can't tell - assume it paints, never under-report
        return True
    for sl in sym_layers:
        if not symbol_layer_enabled(sl):
            continue
        brush = getattr(sl, "brushStyle", None)
        if brush is not None:
            try:
                if brush() == Qt.BrushStyle.NoBrush:
                    continue
            except API_MISS as exc:
                note("symbolLayer.brushStyle()", exc)
        fill = getattr(sl, "fillColor", None)
        try:
            colour = fill() if fill is not None else sl.color()
        except API_MISS as exc:
            note("symbolLayer.fillColor()/color()", exc)
            colour = None
        if colour is not None and colour.alpha() == 0:
            continue
        if fill is not None or brush is not None:
            return True
    return False


def count_in_box(layer, rect, project_crs, cap=COUNT_CAP):
    """Roughly how many features fall in the box, using the layer's index.

    A bounding-box request, so it over-reports features whose envelope clips
    the box but whose geometry does not - close enough for a pre-flight, and
    it costs nothing on an indexed source. Returns (count, capped).
    """
    try:
        box = rect
        if (layer.crs().isValid() and project_crs.isValid()
                and layer.crs() != project_crs):
            tr = QgsCoordinateTransform(project_crs, layer.crs(),
                                        QgsProject.instance())
            box = tr.transformBoundingBox(rect)
        req = QgsFeatureRequest().setFilterRect(box).setNoAttributes()
        flags = getattr(QgsFeatureRequest, "NoGeometry", None)
        if flags is not None:
            req.setFlags(flags)
        n = 0
        for _ in layer.getFeatures(req):
            n += 1
            if n >= cap:
                return n, True
        return n, False
    except API_MISS as exc:
        note("feature count for " + layer.name(), exc)
        return -1, False


def describe(layer, rect, project_crs):
    """One pre-flight row: what this layer is, and what it will produce."""
    gtype = layer.geometryType()
    is_polygon = gtype == QgsWkbTypes.GeometryType.PolygonGeometry
    count, capped = count_in_box(layer, rect, project_crs)

    blocker = ""
    if not layer.isValid():
        blocker = "layer is broken and cannot be read"
    elif not layer.crs().isValid():
        # Left to QGIS this surfaces as an unexplained projection dialog in
        # the middle of the export, with nothing to say which layer caused it.
        blocker = "no CRS - cannot be placed, will be skipped"

    notes = []
    if not blocker:
        if count == 0:
            notes.append("nothing inside the box")
        if is_polygon and not has_visible_fill(layer):
            notes.append("no fill on canvas, so outlines only - no hatches")

    return {
        "layer": layer,
        "name": layer.name(),
        "geometry": QgsWkbTypes.geometryDisplayString(gtype)
                    if gtype is not None else "?",
        "is_polygon": is_polygon,
        "count": count,
        "capped": capped,
        "crs": layer.crs().authid() or layer.crs().description() or "",
        "blocker": blocker,
        "notes": notes,
        "include": not blocker and count != 0,
    }


def preflight(rect, project_crs, project=None):
    """describe() every layer that would be exported, in draw order."""
    return [describe(lyr, rect, project_crs)
            for lyr in export_layers(project)]
