"""GENERATED by ../Clip to DWG/build_standalone.py from
Toms Toolbar/clip_dwg/tool.py - do not edit this copy, edit that one.
"""
"""
Clip to DWG — tool module for Tom's Toolbar.

Click two opposite corners (or click-drag a box) on the map; all visible
vector layers are clipped to that box and exported as a single DWG file via the
ODA File Converter. Originally the standalone "Clip to DWG" plugin; here the
toolbar/menu wiring is owned by the Tom's Toolbar host (plugin.py) and this
module just exposes `self.actions`.

QSettings keys are unchanged (ClipToDwg/...) so an existing ODA path is reused.
"""

import os
import tempfile
import shutil
import subprocess

from qgis.PyQt.QtCore import Qt, QSettings, QFile, QIODevice
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import (
    QAction, QAbstractItemView, QDialog, QDialogButtonBox, QFileDialog,
    QHeaderView, QLabel, QMessageBox, QPushButton, QTableWidget,
    QTableWidgetItem, QVBoxLayout,
)

from qgis.core import (
    QgsProject,
    QgsRectangle,
    QgsGeometry,
    QgsFeature,
    QgsVectorLayer,
    QgsWkbTypes,
    QgsMapLayer,
    QgsUnitTypes,
    QgsDxfExport,
    QgsTask,
    QgsApplication,
    QgsMessageLog,
    QgsRenderContext,
    Qgis,
)

import processing

from .box_map_tool import BoxMapTool
from . import preflight


PLUGIN_NAME = "Clip to DWG"
SETTINGS_ODA_PATH = "ClipToDwg/oda_converter_path"


# ----------------------------------------------------------------------------
# Pre-flight: show exactly what is about to be exported
# ----------------------------------------------------------------------------
class PreflightDialog(QDialog):
    """What is going in, before it goes in.

    Exists because the export used to be silent about its own input: layers
    inside a "Render Layers as a Group" group were dropped without a word, and
    a highlighted-but-unticked layer looked like it would export and did not.
    Listed top-to-bottom exactly as the Layers panel shows them.
    """

    COLS = ("Layer", "Geometry", "In box", "Will produce")

    def __init__(self, rows, parent=None):
        super().__init__(parent)
        self.setWindowTitle(PLUGIN_NAME + " - what will be exported")
        self.resize(720, 420)
        self.rows = rows

        lay = QVBoxLayout(self)
        blurb = QLabel(
            "Everything ticked below goes into the DWG, in this order - the "
            "top of the list ends up on top in CAD, same as the Layers panel. "
            "Counts are from the layer index, so they can be a shade high.")
        blurb.setWordWrap(True)
        lay.addWidget(blurb)

        self.table = QTableWidget(len(rows), len(self.COLS), self)
        self.table.setHorizontalHeaderLabels(self.COLS)
        self.table.verticalHeader().setVisible(False)
        self.table.setSelectionMode(
            QAbstractItemView.SelectionMode.NoSelection)
        self.table.setEditTriggers(
            QAbstractItemView.EditTrigger.NoEditTriggers)
        for r, row in enumerate(rows):
            name = QTableWidgetItem(row["name"])
            name.setFlags(Qt.ItemFlag.ItemIsUserCheckable
                          | Qt.ItemFlag.ItemIsEnabled)
            name.setCheckState(Qt.CheckState.Checked if row["include"]
                               else Qt.CheckState.Unchecked)
            if row["blocker"]:
                # ticking it would not help - the layer cannot be exported
                name.setFlags(Qt.ItemFlag.ItemIsUserCheckable)
            self.table.setItem(r, 0, name)
            self.table.setItem(r, 1, QTableWidgetItem(row["geometry"]))
            count = ("?" if row["count"] < 0
                     else "{:,}{}".format(row["count"],
                                          "+" if row["capped"] else ""))
            self.table.setItem(r, 2, QTableWidgetItem(count))
            if row["blocker"]:
                note = row["blocker"].upper()
            elif row["notes"]:
                note = "; ".join(row["notes"])
            elif row["is_polygon"]:
                note = "hatches + outlines"
            else:
                note = "lines" if row["geometry"] == "Line" else "points"
            self.table.setItem(r, 3, QTableWidgetItem(note))
        header = self.table.horizontalHeader()
        header.setSectionResizeMode(0, QHeaderView.ResizeMode.Stretch)
        for c in (1, 2, 3):
            header.setSectionResizeMode(
                c, QHeaderView.ResizeMode.ResizeToContents)
        lay.addWidget(self.table)

        self.summary = QLabel()
        self.summary.setWordWrap(True)
        lay.addWidget(self.summary)

        buttons = QDialogButtonBox(
            QDialogButtonBox.StandardButton.Ok
            | QDialogButtonBox.StandardButton.Cancel)
        none_btn = QPushButton("Select none")
        none_btn.clicked.connect(
            lambda: self._set_all(Qt.CheckState.Unchecked))
        all_btn = QPushButton("Select all")
        all_btn.clicked.connect(lambda: self._set_all(Qt.CheckState.Checked))
        buttons.addButton(all_btn, QDialogButtonBox.ButtonRole.ActionRole)
        buttons.addButton(none_btn, QDialogButtonBox.ButtonRole.ActionRole)
        buttons.accepted.connect(self.accept)
        buttons.rejected.connect(self.reject)
        lay.addWidget(buttons)
        self._ok = buttons.button(QDialogButtonBox.StandardButton.Ok)

        self.table.itemChanged.connect(self._refresh)
        self._refresh()

    def _set_all(self, state):
        for r, row in enumerate(self.rows):
            if row["blocker"]:
                continue
            self.table.item(r, 0).setCheckState(state)

    def _refresh(self, *_):
        chosen = self.chosen()
        blocked = [r["name"] for r in self.rows if r["blocker"]]
        bits = ["<b>{}</b> layer(s) selected".format(len(chosen))]
        if blocked:
            bits.append('<span style="color:#b36b00">{} unusable: {}</span>'
                        .format(len(blocked), ", ".join(blocked[:3])))
        self.summary.setText(" &nbsp;·&nbsp; ".join(bits))
        self._ok.setEnabled(bool(chosen))

    def chosen(self):
        """Rows the user left ticked, still in panel order."""
        out = []
        for r, row in enumerate(self.rows):
            item = self.table.item(r, 0)
            if (item is not None
                    and item.checkState() == Qt.CheckState.Checked
                    and not row["blocker"]):
                out.append(row)
        return out


# ----------------------------------------------------------------------------
# Background task: run ODA File Converter and move the resulting DWG
# ----------------------------------------------------------------------------
class DwgConvertTask(QgsTask):
    def __init__(self, dxf_dir, output_dwg_path, oda_path):
        super().__init__("Converting DXF to DWG", QgsTask.Flag.CanCancel)
        self.dxf_dir = dxf_dir
        self.output_dwg_path = output_dwg_path
        self.oda_path = oda_path
        self.error = None

    def run(self):
        out_tmpdir = None
        try:
            out_tmpdir = tempfile.mkdtemp(prefix="cliptodwg_out_")
            # ODA File Converter CLI signature:
            #   ODAFileConverter <in_dir> <out_dir> <out_ver> <out_fmt>
            #                    <recurse> <audit> <filter>
            cmd = [
                self.oda_path,
                self.dxf_dir,
                out_tmpdir,
                "ACAD2018",
                "DWG",
                "0",   # do not recurse
                "1",   # audit
                "*.DXF",
            ]
            # nosec B603 - reviewed: list form with shell=False (the default),
            # so nothing in any path is shell-interpreted. oda_path is the
            # executable the user picked in a file dialog and is checked with
            # os.path.exists() before we get here; the two directories are
            # tempfile.mkdtemp() results and every other argument is a literal.
            proc = subprocess.run(                              # noqa: S603
                cmd, capture_output=True, timeout=300, shell=False
            )
            if proc.returncode != 0:
                self.error = (
                    "ODA File Converter exited with code "
                    f"{proc.returncode}: "
                    + proc.stderr.decode(errors="ignore")[:500]
                )
                return False

            produced = os.path.join(out_tmpdir, "out.dwg")
            if not os.path.exists(produced):
                self.error = "ODA File Converter did not produce a DWG."
                return False

            # Replace existing target if any
            if os.path.exists(self.output_dwg_path):
                os.remove(self.output_dwg_path)
            shutil.move(produced, self.output_dwg_path)
            return True
        except subprocess.TimeoutExpired:
            self.error = "ODA File Converter timed out."
            return False
        except Exception as e:
            self.error = str(e)
            return False
        finally:
            shutil.rmtree(self.dxf_dir, ignore_errors=True)
            if out_tmpdir:
                shutil.rmtree(out_tmpdir, ignore_errors=True)


# ----------------------------------------------------------------------------
# Tool
# ----------------------------------------------------------------------------
class ClipToDwgTool:
    def __init__(self, iface):
        self.iface = iface
        self.map_tool = None
        self.previous_tool = None
        self._oda_path = None
        self._report = []       # per-layer accounting for the last export

        icon_path = os.path.join(os.path.dirname(__file__), "icon.svg")
        self.action = QAction(
            QIcon(icon_path), PLUGIN_NAME, self.iface.mainWindow()
        )
        self.action.setToolTip(
            "Clip visible vector layers to a box and export to DWG"
        )
        self.action.triggered.connect(self.start)
        self.actions = [self.action]

    # --- Helpers ------------------------------------------------------------
    def _flash(self, text, level=Qgis.MessageLevel.Info, duration=4):
        self.iface.messageBar().pushMessage(
            PLUGIN_NAME, text, level=level, duration=duration
        )

    def _get_visible_vector_layers(self):
        """Ticked vector layers, top of the Layers panel first.

        NOT `root.checkedLayers()`: once a group is set to "Render Layers as a
        Group" that call returns the group COMPOSITE (a QgsGroupLayer, not a
        vector layer) instead of its children, so a vector-layer filter threw
        the whole group away without a word. See preflight.py.
        """
        return preflight.export_layers()

    def _ensure_oda_path(self):
        s = QSettings()
        path = s.value(SETTINGS_ODA_PATH, "", type=str)
        if path and os.path.exists(path):
            return path

        box = QMessageBox(self.iface.mainWindow())
        box.setIcon(QMessageBox.Icon.Information)
        box.setWindowTitle("ODA File Converter required")
        box.setTextFormat(Qt.TextFormat.RichText)
        box.setTextInteractionFlags(
            Qt.TextInteractionFlag.TextBrowserInteraction)
        box.setText(
            "<p><b>Clip to DWG</b> needs the free "
            "<b>ODA File Converter</b> to produce DWG files. "
            "QGIS and GDAL cannot write DWG natively, so this external "
            "tool is used to convert the intermediate DXF to DWG.</p>"
            "<p>Download it from the Open Design Alliance:<br>"
            '<a href="https://www.opendesign.com/guestfiles/'
            'oda_file_converter">'
            "https://www.opendesign.com/guestfiles/oda_file_converter</a></p>"
            "<p>Install it, then click <b>Select...</b> and point at the "
            "<code>ODAFileConverter</code> executable. The location is "
            "remembered for future runs.</p>"
            "<p>Click <b>Go Back</b> to cancel and come back later.</p>"
        )
        box.addButton("Go Back", QMessageBox.RejectRole)
        select_btn = box.addButton("Select...", QMessageBox.AcceptRole)
        box.setDefaultButton(select_btn)
        box.exec()

        if box.clickedButton() is not select_btn:
            return None

        if os.name == "nt":
            filt = "Executables (*.exe);;All files (*)"
        else:
            filt = "All files (*)"
        new_path, _ = QFileDialog.getOpenFileName(
            self.iface.mainWindow(),
            "Locate ODA File Converter executable",
            "",
            filt,
        )
        if new_path and os.path.exists(new_path):
            s.setValue(SETTINGS_ODA_PATH, new_path)
            return new_path
        self._flash(
            "ODA File Converter path not set. Cancelled.",
            Qgis.MessageLevel.Warning,
        )
        return None

    def _restore_tool(self):
        if self.previous_tool is not None:
            self.iface.mapCanvas().setMapTool(self.previous_tool)
        self.previous_tool = None
        self.map_tool = None

    # --- reporting ----------------------------------------------------------
    def _log_report(self):
        """Per-layer accounting into the log, always. An export that quietly
        drops a layer is the bug this whole pass exists to kill."""
        for r in self._report:
            QgsMessageLog.logMessage(
                "{}: {:,} feature(s) in layer -> {:,} exported{}{}".format(
                    r["name"], r["in"], r["out"],
                    ", with hatches" if r["hatch"] else "",
                    " [{}]".format(r["error"]) if r["error"] else ""),
                PLUGIN_NAME,
                Qgis.MessageLevel.Critical if r["error"]
                else Qgis.MessageLevel.Info)

    def _failure_hint(self):
        """Why an export that found nothing probably found nothing."""
        if not self._report:
            return ""
        if all(r["in"] == 0 for r in self._report):
            return "The chosen layers are empty."
        return ("The box may not overlap them - check the coordinates in the "
                "log panel under '{}'.".format(PLUGIN_NAME))

    # --- Workflow steps -----------------------------------------------------
    def start(self):
        if not self._get_visible_vector_layers():
            self._flash(
                "No ticked vector layers. Tick the layers you want in the "
                "Layers panel - selecting/highlighting them is not enough.",
                Qgis.MessageLevel.Warning, 8)
            return

        oda = self._ensure_oda_path()
        if not oda:
            return
        self._oda_path = oda

        self._flash(
            "Click two opposite corners, or click-drag a box. "
            "Esc or right-click to cancel.",
            Qgis.MessageLevel.Info, 6,
        )
        canvas = self.iface.mapCanvas()
        self.previous_tool = canvas.mapTool()
        self.map_tool = BoxMapTool(
            canvas, self._on_box_drawn, self._on_box_cancelled
        )
        canvas.setMapTool(self.map_tool)

    def _on_box_cancelled(self):
        self._restore_tool()
        self._flash("Cancelled.", Qgis.MessageLevel.Info)

    def _on_box_drawn(self, rect):
        self._restore_tool()

        if rect.width() == 0 or rect.height() == 0:
            self._flash("Nothing chosen: zero area box.",
                        Qgis.MessageLevel.Warning)
            return

        project_crs = QgsProject.instance().crs()
        if not project_crs.isValid():
            self._flash("The project has no valid CRS - set one first.",
                        Qgis.MessageLevel.Critical, 8)
            return

        rows = preflight.preflight(rect, project_crs)
        if not rows:
            self._flash("No ticked vector layers.", Qgis.MessageLevel.Warning)
            return
        dlg = PreflightDialog(rows, self.iface.mainWindow())
        if dlg.exec() != QDialog.DialogCode.Accepted:
            self._flash("Cancelled.", Qgis.MessageLevel.Info)
            return
        chosen = dlg.chosen()
        if not chosen:
            self._flash("Nothing selected to export.",
                        Qgis.MessageLevel.Warning)
            return
        layers = [r["layer"] for r in chosen]

        units = project_crs.mapUnits()
        hint = ("feet" if units == QgsUnitTypes.DistanceUnit.DistanceFeet
                else "meters")

        path, _ = QFileDialog.getSaveFileName(
            self.iface.mainWindow(),
            "Save DWG (coordinates in {})".format(hint),
            "",
            "AutoCAD DWG (*.dwg)",
        )
        if not path:
            self._flash("Save cancelled.", Qgis.MessageLevel.Info)
            return
        if not path.lower().endswith(".dwg"):
            path += ".dwg"

        oda = self._oda_path
        if not oda or not os.path.exists(oda):
            self._flash(
                "ODA File Converter path not set. Aborting.",
                Qgis.MessageLevel.Critical
            )
            return

        # --- Synchronous: clip layers and write temp DXF -------------------
        self._report = []
        try:
            dxf_dir = self._clip_and_write_dxf(layers, rect, project_crs)
        except Exception as e:
            QgsMessageLog.logMessage(
                "Clip/DXF failed: {}".format(e), PLUGIN_NAME,
                Qgis.MessageLevel.Critical
            )
            self._flash(
                "Failed to prepare DXF: {}".format(e),
                Qgis.MessageLevel.Critical, 8
            )
            return

        self._log_report()
        if dxf_dir is None:
            self._flash(
                "No features found within the box. " + self._failure_hint(),
                Qgis.MessageLevel.Warning, 10,
            )
            return
        # A layer that went in and produced nothing must never pass silently -
        # that is how three flood layers became one stray block reference.
        lost = [r for r in self._report if r["error"] or r["out"] == 0]
        if lost:
            self._flash(
                "{} of {} layer(s) produced nothing: {}".format(
                    len(lost), len(self._report),
                    "; ".join("{} ({})".format(
                        r["name"], r["error"] or "no features in the box")
                        for r in lost[:3])),
                Qgis.MessageLevel.Warning, 10,
            )

        # --- Background: ODA conversion ------------------------------------
        task = DwgConvertTask(dxf_dir, path, oda)
        task.taskCompleted.connect(
            lambda t=task, p=path: self._on_task_done(t, p, True)
        )
        task.taskTerminated.connect(
            lambda t=task, p=path: self._on_task_done(t, p, False)
        )
        QgsApplication.taskManager().addTask(task)
        self._flash("Exporting in background...", Qgis.MessageLevel.Info, 3)

    def _clip_and_write_dxf(self, layers, extent, project_crs):
        """Clip layers to extent, write a DXF to a temp dir, return that dir.

        Returns None if there are no features to export.
        """
        # Build an overlay layer holding the bbox polygon in project CRS.
        # NOT "Polygon?crs={authid}": a custom project CRS has an empty
        # authid(), which leaves the memory layer CRS-less and makes QGIS throw
        # a projection dialog in the middle of the export with nothing to say
        # what asked for it. Set the CRS object on the layer instead.
        bbox_geom = QgsGeometry.fromRect(extent)
        bbox_layer = QgsVectorLayer("Polygon", "bbox", "memory")
        bbox_layer.setCrs(project_crs)
        feat = QgsFeature()
        feat.setGeometry(bbox_geom)
        bbox_layer.dataProvider().addFeatures([feat])
        bbox_layer.updateExtents()

        # One entry per source layer, each holding [fill clip, boundary lines].
        # Kept grouped so the DXF can be written bottom-of-panel first (CAD
        # draws later entities on top) while a layer's own hatch still goes
        # down before its outlines.
        groups = []
        for lyr in layers:
            entry = {"name": lyr.name(), "in": lyr.featureCount(),
                     "out": 0, "hatch": False, "error": "", "layers": []}
            self._report.append(entry)
            try:
                is_polygon = (
                    lyr.geometryType()
                    == QgsWkbTypes.GeometryType.PolygonGeometry
                )

                # Pass 1: clip the layer normally. For polygons this gives
                # the fill source for HATCH entities; outline strokes will
                # be suppressed via the cloned renderer below. For lines
                # and points, this is the only pass.
                result = processing.run(
                    "native:clip",
                    {
                        "INPUT": lyr,
                        "OVERLAY": bbox_layer,
                        "OUTPUT": "memory:",
                    },
                )
                clipped = result["OUTPUT"]
                if clipped.featureCount() > 0:
                    entry["out"] += clipped.featureCount()
                    entry["hatch"] = (is_polygon
                                      and preflight.has_visible_fill(lyr))
                    clipped.setName(lyr.name())
                    try:
                        src_renderer = lyr.renderer()
                        if src_renderer is not None:
                            cloned = src_renderer.clone()
                            self._disable_invisible_symbol_layers(cloned)
                            if is_polygon:
                                self._disable_polygon_stroke(cloned)
                            clipped.setRenderer(cloned)
                    except Exception as e:
                        QgsMessageLog.logMessage(
                            "Renderer clone failed for {}: {}".format(
                                lyr.name(), e
                            ),
                            PLUGIN_NAME, Qgis.MessageLevel.Warning,
                        )
                    entry["layers"].append(clipped)

                # Pass 2 (polygons only): convert polygon boundaries to
                # lines first, then clip. Polygons that cross the bbox
                # produce open polylines that stop at the bbox edge
                # instead of closing along it.
                #
                # Pre-filter the source by bbox-intersection using a
                # spatial index (extractbylocation) so polygonstolines
                # only processes nearby polygons instead of every
                # polygon in the layer. Big speedup on wide-area layers.
                if is_polygon:
                    try:
                        subset_result = processing.run(
                            "native:extractbylocation",
                            {
                                "INPUT": lyr,
                                "INTERSECT": bbox_layer,
                                "PREDICATE": [0],
                                "OUTPUT": "memory:",
                            },
                        )
                        subset_layer = subset_result["OUTPUT"]
                        if subset_layer.featureCount() > 0:
                            lines_result = processing.run(
                                "native:polygonstolines",
                                {"INPUT": subset_layer, "OUTPUT": "memory:"},
                            )
                            lines_layer = lines_result["OUTPUT"]
                            clipped_lines_result = processing.run(
                                "native:clip",
                                {
                                    "INPUT": lines_layer,
                                    "OVERLAY": bbox_layer,
                                    "OUTPUT": "memory:",
                                },
                            )
                            clipped_lines = clipped_lines_result["OUTPUT"]
                            if clipped_lines.featureCount() > 0:
                                clipped_lines.setName(lyr.name())
                                entry["out"] += clipped_lines.featureCount()
                                entry["layers"].append(clipped_lines)
                    except Exception as e:
                        entry["error"] = "boundary lines failed: {}".format(e)
                        QgsMessageLog.logMessage(
                            "Boundary line pass failed for {}: {}".format(
                                lyr.name(), e
                            ),
                            PLUGIN_NAME, Qgis.MessageLevel.Warning,
                        )
            except Exception as e:
                entry["error"] = str(e)
                QgsMessageLog.logMessage(
                    "Skipping {}: {}".format(lyr.name(), e),
                    PLUGIN_NAME, Qgis.MessageLevel.Critical,
                )
            if entry["layers"]:
                groups.append(entry["layers"])

        if not groups:
            return None

        # Bottom of the Layers panel first: CAD draws later entities over
        # earlier ones, so this leaves the top of the panel on top in the DWG.
        clipped_layers = [lyr for grp in reversed(groups) for lyr in grp]

        tmpdir = tempfile.mkdtemp(prefix="cliptodwg_")
        try:
            dxf_path = os.path.join(tmpdir, "out.dxf")

            dxf = QgsDxfExport()
            dxf.addLayers([QgsDxfExport.DxfLayer(lyr)
                           for lyr in clipped_layers])
            dxf.setSymbologyExport(
                QgsDxfExport.SymbologyExport.SymbolLayerSymbology)
            try:
                dxf.setSymbologyScale(self.iface.mapCanvas().scale())
            except preflight.API_MISS as exc:
                # symbol sizes fall back to the DXF default scale, which
                # changes line weights in CAD - say so rather than wonder later
                preflight.note("mapCanvas().scale() for symbology scale", exc)
            dxf.setExtent(extent)
            dxf.setDestinationCrs(project_crs)

            f = QFile(dxf_path)
            if not f.open(QIODevice.OpenModeFlag.WriteOnly):
                raise RuntimeError("Could not open temp DXF for writing.")

            try:
                res = dxf.writeToFile(f, "UTF-8")
            finally:
                f.close()

            # Compare against the enum MEMBER, never 0. On PyQt5 the enum
            # is an int subclass so `res != 0` worked; on PyQt6 it is a real
            # Python enum, `Success == 0` is False and int() raises - so a
            # perfectly good export raised "returned error ExportResult.Success".
            if res != QgsDxfExport.ExportResult.Success:
                raise RuntimeError(
                    "QgsDxfExport.writeToFile returned error {}".format(res)
                )
        except Exception:
            shutil.rmtree(tmpdir, ignore_errors=True)
            raise

        try:
            self._drop_invisible_hatches(dxf_path)
        except Exception as e:
            QgsMessageLog.logMessage(
                "Invisible hatch drop failed: {}".format(e),
                PLUGIN_NAME, Qgis.MessageLevel.Warning,
            )

        try:
            self._force_bylayer(dxf_path)
        except Exception as e:
            QgsMessageLog.logMessage(
                "ByLayer scrub failed: {}".format(e),
                PLUGIN_NAME, Qgis.MessageLevel.Warning,
            )

        return tmpdir

    def _disable_polygon_stroke(self, renderer):
        """Suppress outline strokes on polygon fill symbol layers so the
        clipped polygon only emits HATCH (no closed polyline outline along
        the bbox edge). Boundary lines come from the separate boundary
        pass.
        """
        for sl in preflight.symbol_layers(renderer)[1]:
            if hasattr(sl, "setStrokeStyle"):
                try:
                    sl.setStrokeStyle(Qt.PenStyle.NoPen)
                except preflight.API_MISS as exc:
                    # a stroke left on means doubled outlines in CAD, so this
                    # is worth knowing about rather than passing over
                    preflight.note("symbolLayer.setStrokeStyle()", exc)

    def _disable_invisible_symbol_layers(self, renderer):
        """Walk a renderer's symbols and disable any symbol layer that is
        eye-toggled off, has fully transparent colour, or uses NoBrush
        fill style. QgsDxfExport skips disabled symbol layers, so this
        suppresses HATCH output for features the user has hidden.
        """
        for sl in preflight.symbol_layers(renderer)[1]:
            if not preflight.symbol_layer_enabled(sl):
                continue
            if not preflight.paints_nothing(sl):
                continue
            try:
                sl.setEnabled(False)
            except preflight.API_MISS as exc:
                preflight.note("symbolLayer.setEnabled(False)", exc)

    def _drop_invisible_hatches(self, dxf_path):
        """Remove HATCH entities whose DXF transparency (group code 440)
        indicates alpha byte = 0 (fully transparent). Preserves partially
        transparent hatches.
        """
        with open(dxf_path, "rb") as fh:
            raw = fh.read()
        newline = b"\r\n" if b"\r\n" in raw else b"\n"
        lines = raw.split(newline)

        out = []
        i = 0
        n = len(lines)
        while i < n - 1:
            code = lines[i].strip().decode("ascii", errors="replace")
            value = lines[i + 1].strip().decode("ascii", errors="replace")

            if code == "0" and value == "HATCH":
                buf = [lines[i], lines[i + 1]]
                j = i + 2
                alpha = None
                while j < n - 1:
                    ec = lines[j].strip().decode("ascii", errors="replace")
                    if ec == "0":
                        break
                    ev = lines[j + 1].strip().decode("ascii", errors="replace")
                    if ec == "440":
                        try:
                            alpha = int(ev) & 0xFF
                        except ValueError:
                            pass
                    buf.append(lines[j])
                    buf.append(lines[j + 1])
                    j += 2

                if alpha == 0:
                    # Skip writing this entity entirely
                    pass
                else:
                    out.extend(buf)
                i = j
                continue

            out.append(lines[i])
            out.append(lines[i + 1])
            i += 2

        if i == n - 1:
            out.append(lines[i])

        with open(dxf_path, "wb") as fh:
            fh.write(newline.join(out))

    def _force_bylayer(self, dxf_path):
        """Strip per-entity color/linetype/lineweight overrides in ENTITIES
        and BLOCKS sections so non-hatch entities default to ByLayer.
        HATCH entities are left untouched so fill colour, pattern, and
        transparency (group code 440) survive. Polyline width codes are
        also stripped so polylines render at width 0.
        """
        # Group codes scrubbed from non-hatch entities:
        # 62 color index, 420 true color, 430 color name,
        # 440 transparency, 6 linetype, 370 lineweight
        scrub = {"62", "420", "430", "440", "6", "370"}
        keep_types = {"HATCH"}
        # Type-specific scrub: codes whose meaning depends on entity type.
        # LWPOLYLINE: 43 constant width, 40 start width, 41 end width.
        # POLYLINE: 40 start width, 41 end width (per vertex via VERTEX).
        # VERTEX (sub-entity of POLYLINE): 40 start width, 41 end width.
        type_specific_scrub = {
            "LWPOLYLINE": {"43", "40", "41"},
            "POLYLINE": {"40", "41"},
            "VERTEX": {"40", "41"},
        }

        with open(dxf_path, "rb") as fh:
            raw = fh.read()
        newline = b"\r\n" if b"\r\n" in raw else b"\n"
        lines = raw.split(newline)

        out = []
        section_pending = False
        in_scrub_section = False
        current_entity = None

        i = 0
        n = len(lines)
        while i < n - 1:
            code = lines[i].strip().decode("ascii", errors="replace")
            value = lines[i + 1].strip().decode("ascii", errors="replace")

            if code == "0" and value == "SECTION":
                section_pending = True
                current_entity = None
            elif section_pending and code == "2":
                in_scrub_section = value in ("ENTITIES", "BLOCKS")
                section_pending = False
            elif code == "0" and value == "ENDSEC":
                in_scrub_section = False
                current_entity = None
            elif code == "0" and in_scrub_section:
                current_entity = value

            if in_scrub_section and current_entity not in keep_types:
                if code in scrub:
                    i += 2
                    continue
                extra = type_specific_scrub.get(current_entity)
                if extra and code in extra:
                    i += 2
                    continue

            out.append(lines[i])
            out.append(lines[i + 1])
            i += 2

        # Trailing line if odd count
        if i == n - 1:
            out.append(lines[i])

        with open(dxf_path, "wb") as fh:
            fh.write(newline.join(out))

    def _on_task_done(self, task, path, ok):
        if ok and not task.error:
            self._flash("Saved: {}".format(path), Qgis.MessageLevel.Success, 6)
        else:
            self._flash(
                "Export failed: {}".format(task.error or "unknown error"),
                Qgis.MessageLevel.Critical, 8,
            )
